[Feature] Implement Babybear in ECC
PolyhedraZK/ExpanderCompilerCollection pull request #22
Opened 2024-09-13 22:22 UTC by enpsi20481

Implement babybear field in ECC.

2024-09-14 22:44 UTC, niconiconi requested changes

2024-09-14 22:44 UTC, niconiconi commented on field/babybear/field.go
> +	// return constraint.Element{ab.Uint64()}
remove these comments

2024-09-15 15:21 UTC, siq1 commented
Currently Expander doesn't support babybear field, so it's meaningless to provide support only in the compiler.

2024-09-15 15:55 UTC, enpsi20481 commented
> Currently Expander doesn't support babybear field, so it's meaningless to provide support only in the compiler.

There is a parallel PR here: https://github.com/PolyhedraZK/Expander/pull/92

2024-09-15 16:01 UTC, enpsi20481 commented
@niconiconi  comments addressed

2024-09-18 15:00 UTC, enpsi20481 commented
will submit another PR after rebasing with the master.

2024-09-18 15:00 UTC, closed without merging