Test sha256
PolyhedraZK/ExpanderCompilerCollection pull request #59
Opened 2024-12-24 21:50 UTC by zhiyong1997

2025-01-16 09:01 UTC, zhiyong1997 commented
There seems to be a CI issue in MPI compilation.

2025-01-19 14:58 UTC, siq1 approved these changes

2025-01-19 15:07 UTC, siq1 requested changes
In the two versions of sha256_gf2 (vanilla and crosslayer), the constants are different.
You can see it here 
https://github.com/PolyhedraZK/ExpanderCompilerCollection/commit/fda2f950f8e36048a01443f8065c2bfae1cf3650#diff-adfcebaaa7e5d4d3428596995a0bd21145eccb7fea3d521448ed29a7d07a3bdbL65

Please check the circuit and other constants

2025-01-21 06:00 UTC, zhiyong1997 commented
I accidentally applied clippy auto fix to all files. It's not intended, but the changes seem reasonable. Please feel free to change it back if you find it incorrect.

2025-01-22 01:48 UTC, siq1 approved these changes

2025-01-22 01:49 UTC, merged